export default {
  GET_SETTINGS: "GET_SETTINGS",
  GET_CANVAS: "GET_CANVAS",
  GET_CANVAS_CODE: "GET_CANVAS_CODE",
  CANVAS_AUTH: "CANVAS_AUTH",
  CANVAS_COURSES: "CANVAS_COURSES",
  SYNC_COURSES: "SYNC_COURSES",
  SET_CANVAS_COURSES: "SET_CANVAS_COURSES",
};
